# Download pdf files

This scripts iterates over the relevant cases, including the hyperlink where the pdf file is stored. Then it downloads all files into the designated download folder.

In [8]:
import os
import pandas as pd
import wget
import requests
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [2]:
# show all outputs of cell, not merely of last line (i.e. default of Jupyter Notebook)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
# change working directory + set download location
data_location = "../data"
download_folder = "../data/CC_judgments_pdf"
overview_filename = 'CC_2025-2025.pkl'

In [ ]:
# read in data file
overview_df = pd.read_pickle(os.path.join(data_location, overview_filename))
overview_df.head()

,case number,role number,date,type procedure,controlled norm,outcome,keywords,url
0,61/2025,[8423],03/04/2025,Beroep tot vernietiging,Wetten en procedures inzake gedeeltelijke verb...,Verwerping van het beroep,"[Voorafgaande rechtspleging, Beroep tot vernie...",www.const-court.be/public/n/2025/2025-061n.pdf
1,60/2025,[8286],03/04/2025,Prejudiciële vraag,"Wetboek van economisch recht (artikel I.1, eer...",Onontvankelijkheid van de prejudiciële vraag,"[Economisch recht, Insolventie van onderneming...",www.const-court.be/public/n/2025/2025-060n.pdf

In [ ]:
# Add https to the URLS (to errors regarding scheme-less URLs)
overview_df['url'] = overview_df['url'].apply(lambda x: x if x.startswith('https://') else 'https://' + x)
overview_df.head()

,case number,role number,date,type procedure,controlled norm,outcome,keywords,url
0,61/2025,[8423],03/04/2025,Beroep tot vernietiging,Wetten en procedures inzake gedeeltelijke verb...,Verwerping van het beroep,"[Voorafgaande rechtspleging, Beroep tot vernie...",https://www.const-court.be/public/n/2025/2025-...
1,60/2025,[8286],03/04/2025,Prejudiciële vraag,"Wetboek van economisch recht (artikel I.1, eer...",Onontvankelijkheid van de prejudiciële vraag,"[Economisch recht, Insolventie van onderneming...",https://www.const-court.be/public/n/2025/2025-...
2,59/2025,[8285],03/04/2025,Beroep tot vernietiging,Ordonnantie van het Brusselse Hoofdstedelijke ...,Vernietiging,"[Fiscaal recht, Registratierechten, Brusselse ...",https://www.const-court.be/public/n/2025/2025-...
3,58/2025,[8266],03/04/2025,Beroep tot vernietiging,Programmawet van 22 december 2023 (artikel 114),Verwerping van het beroep,"[Sociaal recht, Sociale zekerheid, Ziekte- en ...",https://www.const-court.be/public/n/2025/2025-...
4,57/2025,"[8224, 8223]",03/04/2025,Prejudiciële vragen,Wet van 17 april 1878 « houdende de voorafgaan...,Geen schending (artikel 26 van de wet van 17 a...,"[Sociale zekerheid, Ziekte- en invaliditeitsve...",https://www.const-court.be/public/n/2025/2025-...

In [11]:
# download pdfs based on all relevant urls to download_folder
for url in overview_df["url"]:
   wget.download(url, download_folder)
print("{} judgments downloaded".format(len(overview_df["url"])))

'../data/CC_judgments_pdf/2025-061n.pdf'

'../data/CC_judgments_pdf/2025-060n.pdf'

'../data/CC_judgments_pdf/2025-059n.pdf'

'../data/CC_judgments_pdf/2025-058n.pdf'

'../data/CC_judgments_pdf/2025-057n.pdf'

'../data/CC_judgments_pdf/2025-056n.pdf'

'../data/CC_judgments_pdf/2025-055n.pdf'

'../data/CC_judgments_pdf/2025-054n.pdf'

'../data/CC_judgments_pdf/2025-053n.pdf'

'../data/CC_judgments_pdf/2025-052n.pdf'

'../data/CC_judgments_pdf/2025-051n.pdf'

'../data/CC_judgments_pdf/2025-050n.pdf'

'../data/CC_judgments_pdf/2025-049n.pdf'

'../data/CC_judgments_pdf/2025-048n.pdf'

'../data/CC_judgments_pdf/2025-047n.pdf'

'../data/CC_judgments_pdf/2025-046n.pdf'

'../data/CC_judgments_pdf/2025-045n.pdf'

'../data/CC_judgments_pdf/2025-044n.pdf'

'../data/CC_judgments_pdf/2025-043n.pdf'

'../data/CC_judgments_pdf/2025-042n.pdf'

'../data/CC_judgments_pdf/2025-041n.pdf'

'../data/CC_judgments_pdf/2025-040n.pdf'

'../data/CC_judgments_pdf/2025-039n.pdf'

'../data/CC_judgments_pdf/2025-038n.pdf'

'../data/CC_judgments_pdf/2025-037n.pdf'

'../data/CC_judgments_pdf/2025-036n.pdf'

'../data/CC_judgments_pdf/2025-035n.pdf'

'../data/CC_judgments_pdf/2025-034n.pdf'

'../data/CC_judgments_pdf/2025-033n.pdf'

'../data/CC_judgments_pdf/2025-032n.pdf'

'../data/CC_judgments_pdf/2025-031n.pdf'

'../data/CC_judgments_pdf/2025-030n.pdf'

'../data/CC_judgments_pdf/2025-029n.pdf'

'../data/CC_judgments_pdf/2025-028n.pdf'

'../data/CC_judgments_pdf/2025-027n.pdf'

'../data/CC_judgments_pdf/2025-026n.pdf'

'../data/CC_judgments_pdf/2025-025n.pdf'

'../data/CC_judgments_pdf/2025-024n.pdf'

'../data/CC_judgments_pdf/2025-023n.pdf'

'../data/CC_judgments_pdf/2025-022n.pdf'

'../data/CC_judgments_pdf/2025-021n.pdf'

'../data/CC_judgments_pdf/2025-020n.pdf'

'../data/CC_judgments_pdf/2025-019n.pdf'

'../data/CC_judgments_pdf/2025-018n.pdf'

'../data/CC_judgments_pdf/2025-017n.pdf'

'../data/CC_judgments_pdf/2025-016n.pdf'

'../data/CC_judgments_pdf/2025-015n.pdf'

'../data/CC_judgments_pdf/2025-014n.pdf'

'../data/CC_judgments_pdf/2025-013n.pdf'

'../data/CC_judgments_pdf/2025-012n.pdf'

'../data/CC_judgments_pdf/2025-011n.pdf'

'../data/CC_judgments_pdf/2025-010n.pdf'

'../data/CC_judgments_pdf/2025-009n.pdf'

'../data/CC_judgments_pdf/2025-008n.pdf'

'../data/CC_judgments_pdf/2025-007n.pdf'

'../data/CC_judgments_pdf/2025-006n.pdf'

'../data/CC_judgments_pdf/2025-005n.pdf'

'../data/CC_judgments_pdf/2025-004n.pdf'

'../data/CC_judgments_pdf/2025-003n.pdf'

'../data/CC_judgments_pdf/2025-002n.pdf'

'../data/CC_judgments_pdf/2025-001n.pdf'

61 judgments downloaded

## Test chunks

In [ ]:
overzicht.shape